Partie 1 – Exploration du dataset
Développer un programme Python capable de récupérer, pour chaque image, son nom, sa classe,
son format, son mode, sa largeur, sa hauteur, l’écart-type de ses pixels, son nombre de canaux et sa
taille.
NB : prendre en charge aussi les fichiers corrompus

In [ ]:
#1. Importer les bibliothèques
# Bibliothèque pour manipuler les chemins et les dossiers
from pathlib import Path

# Bibliothèque pour lire et vérifier les images
from PIL import Image, UnidentifiedImageError

# Bibliothèque pour effectuer des calculs numériques
import numpy as np

# Bibliothèque pour créer et manipuler des tableaux de données
import pandas as pd

#2. definir le chemin du dataset
# Chemin vers le dossier contenant les images originales
RAW_DIR = Path("../data/raw")


#3. Fonction pour analyser une image
def analyser_image(image_path):
    """
    Récupère les informations demandées pour une image.
    Les images corrompues sont prises en charge.
    """

    # Informations par défaut
    informations = {
        "nom": image_path.name,
        "classe": image_path.parent.name,
        "format": None,
        "mode": None,
        "largeur": None,
        "hauteur": None,
        "ecart_type_pixels": None,
        "nombre_canaux": None,
        "taille": image_path.stat().st_size,
        "corrompue": False
    }

    try:
        # Ouverture de l'image
        with Image.open(image_path) as image:

            # Conversion de l'image en tableau NumPy
            pixels = np.array(image)

            # Récupération du format
            informations["format"] = image.format

            # Récupération du mode
            informations["mode"] = image.mode

            # Récupération de la largeur
            informations["largeur"] = image.width

            # Récupération de la hauteur
            informations["hauteur"] = image.height

            # Calcul de l'écart-type des pixels
            informations["ecart_type_pixels"] = pixels.std()

            # Récupération du nombre de canaux
            informations["nombre_canaux"] = len(image.getbands())

    except (UnidentifiedImageError, OSError, ValueError):

        # Si l'image ne peut pas être lue,
        # elle est considérée comme corrompue
        informations["corrompue"] = True

    return informations

In [9]:
#4. Parcourir toutes les images du dataset
# Liste qui contiendra les informations de toutes les images
resultats = []

# Parcours des dossiers de classes
for classe_dir in RAW_DIR.iterdir():

    # Vérifie qu'il s'agit bien d'un dossier
    if classe_dir.is_dir():

        # Parcours des fichiers du dossier
        for image_path in classe_dir.iterdir():

            # Vérifie qu'il s'agit bien d'un fichier
            if image_path.is_file():

                # Analyse de l'image
                informations = analyser_image(image_path)

                # Ajout des informations à la liste
                resultats.append(informations)

In [6]:
#5. Créer le tableau d'exploration
# Transformation de la liste en DataFrame
df_images = pd.DataFrame(resultats)

# Affichage des premières lignes
df_images.head()

,nom,classe,format,mode,largeur,hauteur,ecart_type_pixels,nombre_canaux,taille,corrompue
0,cardboard1.jpg,cardboard,JPEG,RGB,512.0,384.0,40.588529,3.0,17333,False
1,cardboard10.jpg,cardboard,JPEG,RGB,512.0,384.0,42.571288,3.0,21683,False
2,cardboard100.jpg,cardboard,JPEG,RGB,512.0,384.0,46.108305,3.0,14884,False
3,cardboard101.jpg,cardboard,JPEG,RGB,512.0,384.0,72.263996,3.0,14289,False
4,cardboard102.jpg,cardboard,JPEG,RGB,512.0,384.0,48.388937,3.0,18015,False

In [8]:
# Afficher le DataFrame complet
df_images

,nom,classe,format,mode,largeur,hauteur,ecart_type_pixels,nombre_canaux,taille,corrompue
0,cardboard1.jpg,cardboard,JPEG,RGB,512.0,384.0,40.588529,3.0,17333,False
1,cardboard10.jpg,cardboard,JPEG,RGB,512.0,384.0,42.571288,3.0,21683,False
2,cardboard100.jpg,cardboard,JPEG,RGB,512.0,384.0,46.108305,3.0,14884,False
3,cardboard101.jpg,cardboard,JPEG,RGB,512.0,384.0,72.263996,3.0,14289,False
4,cardboard102.jpg,cardboard,JPEG,RGB,512.0,384.0,48.388937,3.0,18015,False
...,...,...,...,...,...,...,...,...,...,...
1027,trash50.jpg,trash,JPEG,RGB,512.0,384.0,41.780027,3.0,13563,False
1028,trash6.jpg,trash,JPEG,RGB,512.0,384.0,37.391702,3.0,10534,False
1029,trash7.jpg,trash,JPEG,RGB,512.0,384.0,41.297376,3.0,8011,False
1030,trash8.jpg,trash,JPEG,RGB,512.0,384.0,47.635953,3.0,16946,False
1031,trash9.jpg,trash,JPEG,RGB,512.0,384.0,67.506557,3.0,13571,False

Partie 2 – Détecter les images corrompues
Écrire et se servir d’une fonction qui détecte une image corrompue

In [10]:
#1. Fonction de détection
def image_corrompue(image_path):
    """
    Vérifie si une image est corrompue.

    Retourne :
    True  -> image corrompue
    False -> image valide
    """

    try:
        # Ouverture de l'image
        with Image.open(image_path) as image:

            # Vérification de l'intégrité du fichier
            image.verify()

        # Aucune erreur : l'image est valide
        return False

    except (UnidentifiedImageError, OSError, ValueError):

        # Une erreur signifie que l'image est corrompue
        return True

In [11]:
#2. Utiliser la fonction sur toutes les images

# Liste des images corrompues
images_corrompues = []

# Parcours des dossiers de classes
for classe_dir in RAW_DIR.iterdir():

    if classe_dir.is_dir():

        # Parcours des fichiers
        for image_path in classe_dir.iterdir():

            if image_path.is_file():

                # Vérification de l'image
                if image_corrompue(image_path):

                    # Ajouter l'image à la liste
                    images_corrompues.append(image_path)

In [13]:
#3. Afficher les images corrompues
# Afficher le nombre d'images corrompues
print("Nombre d'images corrompues :", len(images_corrompues))

# Afficher le chemin de chaque image corrompue
for image_path in images_corrompues:
    print(image_path)

Nombre d'images corrompues : 6
..\data\raw\cardboard\cardboard83.jpg
..\data\raw\glass\glass74.jpg
..\data\raw\metal\metal48.jpg
..\data\raw\paper\paper213.jpg
..\data\raw\plastic\plastic13.jpg
..\data\raw\trash\trash3.jpg

In [15]:
#4. Vérification dans notre DataFrame
# Compter les images corrompues
df_images["corrompue"].sum()

np.int64(6)

Partie 3 – Détecter les images vides
Écrire et se servir d’une fonction qui détecte les images vides : image entièrement noire, image
entièrement blanche ou image dont les pixels présentent très peu de variation.

In [16]:
#1. Fonction de détection
def image_vide(image_path, seuil_variation=5):
    """
    Détecte si une image est vide.

    Une image est considérée comme vide si :
    - elle est entièrement noire ;
    - elle est entièrement blanche ;
    - ses pixels présentent très peu de variation.

    Retourne True si l'image est vide, sinon False.
    """

    try:
        # Ouvrir l'image
        with Image.open(image_path) as image:

            # Convertir l'image en niveaux de gris
            # afin de travailler avec une seule valeur par pixel
            image = image.convert("L")

            # Transformer l'image en tableau NumPy
            pixels = np.array(image)

            # Calculer la valeur minimale et maximale des pixels
            valeur_min = pixels.min()
            valeur_max = pixels.max()

            # Calculer l'écart-type des pixels
            ecart_type = pixels.std()

            # Vérifier si l'image est entièrement noire
            noire = valeur_max == 0

            # Vérifier si l'image est entièrement blanche
            blanche = valeur_min == 255

            # Vérifier si les pixels présentent très peu de variation
            faible_variation = ecart_type < seuil_variation

            # L'image est vide si au moins une condition est vraie
            return noire or blanche or faible_variation

    except (UnidentifiedImageError, OSError, ValueError):

        # Une image corrompue n'est pas considérée comme une image vide
        return False

In [17]:
#2. Utiliser la fonction sur le dataset
# Liste qui contiendra les images vides
images_vides = []

# Parcourir les dossiers de classes
for classe_dir in RAW_DIR.iterdir():

    if classe_dir.is_dir():

        # Parcourir les fichiers
        for image_path in classe_dir.iterdir():

            if image_path.is_file():

                # Vérifier si l'image est vide
                if image_vide(image_path):

                    # Ajouter l'image à la liste
                    images_vides.append(image_path)

In [19]:
#3. Afficher le résultat
# Afficher le nombre d'images vides
print("Nombre d'images vides :", len(images_vides))

# Afficher le chemin de chaque image vide
for image_path in images_vides:
    print(image_path)

Nombre d'images vides : 4
..\data\raw\cardboard\image-blanche-512x384.jpg
..\data\raw\glass\image-noire-512x384.png
..\data\raw\metal\image-blanche-512x384.jpg
..\data\raw\metal\image-noire-512x384.png

Partie 4 – Détecter les différences de résolution

In [ ]:
#1. resolution minimale

# Supprimer les lignes correspondant aux images corrompues
# car leur largeur et leur hauteur sont inconnues
df_valides = df_images[df_images["corrompue"] == False].copy()

In [21]:
# Trouver la largeur minimale
largeur_min = df_valides["largeur"].min()

# Trouver la hauteur minimale
hauteur_min = df_valides["hauteur"].min()

print("Largeur minimale :", largeur_min)
print("Hauteur minimale :", hauteur_min)

Largeur minimale : 32.0
Hauteur minimale : 32.0

In [24]:
#2 — Déterminer la résolution maximale
# Trouver la largeur maximale
largeur_max = df_valides["largeur"].max()

# Trouver la hauteur maximale
hauteur_max = df_valides["hauteur"].max()

print("Largeur maximale :", largeur_max)
print("Hauteur maximale :", hauteur_max)

print(
    "Résolution maximale :",
    largeur_max,
    "x",
    hauteur_max
)

Largeur maximale : 512.0
Hauteur maximale : 384.0
Résolution maximale : 512.0 x 384.0

In [27]:
#3 — Nombre d'images par résolution
# Créer une colonne contenant la résolution sous la forme largeur x hauteur
df_valides["resolution"] = (
    df_valides["largeur"].astype(int).astype(str)
    + " x "
    + df_valides["hauteur"].astype(int).astype(str)
)

# Compter le nombre d'images pour chaque résolution
nombre_par_resolution = df_valides["resolution"].value_counts()

print(nombre_par_resolution)

resolution
512 x 384    1013
32 x 32         5
48 x 32         4
40 x 40         4
Name: count, dtype: int64

In [28]:
#4 — Les résolutions les plus fréquentes
# Afficher les 10 résolutions les plus fréquentes
resolutions_frequentes = df_valides["resolution"].value_counts().head(10)

print(resolutions_frequentes)

resolution
512 x 384    1013
32 x 32         5
48 x 32         4
40 x 40         4
Name: count, dtype: int64

In [29]:
#5 — Identifier les images inférieures à 64 × 64
# Identifier les images qui ne respectent pas la contrainte 64 x 64
images_trop_petites = df_valides[
    (df_valides["largeur"] < 64) |
    (df_valides["hauteur"] < 64)
]

In [32]:
# Afficher les images trop petites
images_trop_petites[
    [
        "nom",
        "classe",
        "largeur",
        "hauteur",
        "resolution"
    ]
]

                  nom     classe  largeur  hauteur resolution
20   cardboard117.jpg  cardboard     48.0     32.0    48 x 32
77    cardboard22.jpg  cardboard     32.0     32.0    32 x 32
133   cardboard70.jpg  cardboard     40.0     40.0    40 x 40
171      glass100.jpg      glass     40.0     40.0    40 x 40
229       glass15.jpg      glass     48.0     32.0    48 x 32
268       glass21.jpg      glass     32.0     32.0    32 x 32
270       glass23.jpg      glass     32.0     32.0    32 x 32
383      metal121.jpg      metal     48.0     32.0    48 x 32
413        metal2.jpg      metal     32.0     32.0    32 x 32
421       metal26.jpg      metal     40.0     40.0    40 x 40
507       paper10.jpg      paper     32.0     32.0    32 x 32
707       paper54.jpg      paper     40.0     40.0    40 x 40
718       paper64.jpg      paper     48.0     32.0    48 x 32

In [ ]:
# Nombre total d'images trop petites
print(
    "Nombre d'images trop petites :",
    len(images_trop_petites)
)

Partie 5 – Détecter les différents canaux

Déterminer le nombre d'images selon leur nombre de canaux.

In [33]:
##1 — Nombre d'images par nombre de canaux
# Compter le nombre d'images pour chaque nombre de canaux
nombre_par_canaux = df_valides["nombre_canaux"].value_counts().sort_index()

print(nombre_par_canaux)

nombre_canaux
1.0       2
3.0    1006
4.0      18
Name: count, dtype: int64

In [34]:
#2 — Afficher de manière plus claire
# Afficher le nombre d'images pour chaque nombre de canaux
for nombre_canaux, nombre_images in nombre_par_canaux.items():

    print(
        nombre_images,
        "images avec",
        nombre_canaux,
        "canal(aux)"
    )

2 images avec 1.0 canal(aux)
1006 images avec 3.0 canal(aux)
18 images avec 4.0 canal(aux)

In [35]:
#3 — Vérifier les modes correspondants
# Afficher le nombre d'images pour chaque mode
print(df_valides["mode"].value_counts())

mode
RGB     1006
RGBA      18
P          2
Name: count, dtype: int64

In [ ]:
#Partie 6 – Détecter les doublons

Écrire et se servir d’une fonction qui détecte les doublons
NB : Deux fichiers différents peuvent contenir exactement la même image.

In [37]:
#1.importation
import hashlib

In [39]:
#2. Fonction pour calculer le hash
def calculer_hash(image_path):
    """
    Calcule le hash MD5 du contenu d'une image.
    """

    # Créer un objet MD5
    hash_md5 = hashlib.md5()

    # Ouvrir l'image en mode binaire
    with open(image_path, "rb") as fichier:

        # Lire le fichier par morceaux
        for bloc in iter(lambda: fichier.read(4096), b""):

            # Ajouter le bloc au hash
            hash_md5.update(bloc)

    # Retourner le hash sous forme de texte
    return hash_md5.hexdigest()

In [40]:
#3. Fonction pour détecter les doublons
def detecter_doublons(raw_dir):
    """
    Détecte les fichiers qui possèdent exactement le même contenu.
    """

    # Dictionnaire :
    # clé   = hash
    # valeur = liste des fichiers correspondants
    hashes = {}

    # Parcourir les dossiers de classes
    for classe_dir in raw_dir.iterdir():

        if classe_dir.is_dir():

            # Parcourir les fichiers
            for image_path in classe_dir.iterdir():

                if image_path.is_file():

                    # Calculer le hash de l'image
                    hash_image = calculer_hash(image_path)

                    # Ajouter le fichier au dictionnaire
                    hashes.setdefault(hash_image, []).append(image_path)

    # Conserver uniquement les groupes contenant plusieurs fichiers
    doublons = {
        hash_value: fichiers
        for hash_value, fichiers in hashes.items()
        if len(fichiers) > 1
    }

    return doublons

In [41]:
#4. Utiliser la fonction
# Détecter les doublons
doublons = detecter_doublons(RAW_DIR)

# Afficher les doublons
for hash_value, fichiers in doublons.items():

    print("Doublon détecté :")

    for fichier in fichiers:
        print("   ", fichier)

    print()

Doublon détecté :
    ..\data\raw\cardboard\image-blanche-512x384.jpg
    ..\data\raw\metal\image-blanche-512x384.jpg

Doublon détecté :
    ..\data\raw\cardboard\image-violet-512x384.gif
    ..\data\raw\glass\image-violet-512x384.gif

Doublon détecté :
    ..\data\raw\glass\glass115.jpg
    ..\data\raw\metal\metal91.jpg

Doublon détecté :
    ..\data\raw\glass\glass176.jpg
    ..\data\raw\plastic\plastic152.jpg

Doublon détecté :
    ..\data\raw\glass\image-noire-512x384.png
    ..\data\raw\metal\image-noire-512x384.png

Doublon détecté :
    ..\data\raw\metal\metal125.jpg
    ..\data\raw\metal\metal125po.jpg

Doublon détecté :
    ..\data\raw\metal\metal35.jpg
    ..\data\raw\metal\metal35rt.jpg

Doublon détecté :
    ..\data\raw\metal\metal65.jpg
    ..\data\raw\metal\metalyu65.jpg

Doublon détecté :
    ..\data\raw\paper\paper221.jpg
    ..\data\raw\paper\paper221kl.jpg

Doublon détecté :
    ..\data\raw\paper\paper35.jpg
    ..\data\raw\paper\paperer35.jpg

Doublon détecté :
    ..\data\raw\paper\paper77.jpg
    ..\data\raw\paper\paper77ty.jpg

Doublon détecté :
    ..\data\raw\plastic\plastic140.jpg
    ..\data\raw\plastic\plastic140y.jpg

Doublon détecté :
    ..\data\raw\plastic\plastic171.jpg
    ..\data\raw\plastic\plastic171az.jpg

Doublon détecté :
    ..\data\raw\plastic\plastic199.jpg
    ..\data\raw\plastic\plasticx199.jpg

Doublon détecté :
    ..\data\raw\plastic\plastic36.jpg
    ..\data\raw\plastic\plastic36rt.jpg